// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3mE7ZCh3jGH51mR3d3_Dsgnk02sOGQA',
    appId: '1:316328180124:web:d0314139a0640ba3027059',
    messagingSenderId: '316328180124',
    projectId: 'psg-fan-quiz',
    authDomain: 'psg-fan-quiz.firebaseapp.com',
    storageBucket: 'psg-fan-quiz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTL3WdLtmSnVMOVlYLoriiRc_dRmn-vm0',
    appId: '1:316328180124:android:a0d1235fb2696599027059',
    messagingSenderId: '316328180124',
    projectId: 'psg-fan-quiz',
    storageBucket: 'psg-fan-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU977XwY8ow62wFCptNNCorihGWt6IH5Y',
    appId: '1:316328180124:ios:d52ce50d1f9b431a027059',
    messagingSenderId: '316328180124',
    projectId: 'psg-fan-quiz',
    storageBucket: 'psg-fan-quiz.firebasestorage.app',
    iosBundleId: 'com.psgfanquiz.psgFanQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU977XwY8ow62wFCptNNCorihGWt6IH5Y',
    appId: '1:316328180124:ios:d52ce50d1f9b431a027059',
    messagingSenderId: '316328180124',
    projectId: 'psg-fan-quiz',
    storageBucket: 'psg-fan-quiz.firebasestorage.app',
    iosBundleId: 'com.psgfanquiz.psgFanQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA3mE7ZCh3jGH51mR3d3_Dsgnk02sOGQA',
    appId: '1:316328180124:web:0342c03ba2685513027059',
    messagingSenderId: '316328180124',
    projectId: 'psg-fan-quiz',
    authDomain: 'psg-fan-quiz.firebaseapp.com',
    storageBucket: 'psg-fan-quiz.firebasestorage.app',
  );
}
